#url: http://jonkonrath.com/wordpress
name: Jonathan Konrath
description: >
  Technical Writer, Docs Manager,
  Publications Engineer


title: Jonathan Konrath
#email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: jonkonrath
github_username:  jkonrath
linkedin_username: jkonrath

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
